name: morphy
description: Provides a clean class definition with extra functionality including; copy with, json serializable, tostring, equals that supports inheritance and polymorphism
version: 1.4.2+2
homepage: https://github.com/atreeon/morphy

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer:
  build: 
  source_gen: 
  morphy_annotation: ^1.4.2
  dartx: ^1.2.0

dev_dependencies:
  test: ^1.25.0

#  morphy_annotation: ^1.4.2

#    path: ../morphy_annotation
#  morphy_annotation:
#    git:
#      url: https://github.com/atreeon/morphy.git
#      ref: toString2
#      path: morphy_annotation

#dependency_overrides:
#  morphy_annotation:
#    path: ../morphy_annotation

